name: 'Get & Cache Dependencies'
description: 'Get and cache dependencies for a Node.js project'
inputs:
  caching:
    description: 'Whether to cache dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm install
      working-directory: ./practice-react-app
      shell: bash