name: Custom Actions Project
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Run tests
        run: npm test
        working-directory: ./second-app-react
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
        with:
          caching: 'false'
      - name: Build project
        run: npm run build
        working-directory: ./second-app-react
      - name: Deploy
        run: echo "Deploying project"