name: Reusable Deploy # We don't want to run this workflow on every push. But we want it to be called by other workflows.
on: 
    workflow_call:
        inputs: 
            artifact-name:
                description: The name of the deployable artifact files
                required: false
                default: dist
                type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name }}
            - name: List files
              run: ls
            - name: Output information
              run: echo "Deploying & Updating..."